### ISSUE TITLE
React Native Upgrade 0.76.6 to 0.77 - Build Fails with Kotlin Compilation Errors

### ISSUE THREAD

**Issue by mickyfazler** [react-native-menu/menu#1021]
After upgrading React Native from version 0.76.6 to 0.77, my Android build fails with Kotlin compilation errors. The errors appear to originate from dependencies `react-native-menu_menu` and `@shopify/flash-list`.

**To Reproduce:**

1. Upgrade React Native to 0.77
2. Run `npx react-native run-android`

**Expected behavior:**

The Android app should build and install successfully.

**Screenshots/Error Logs:**

```
> Task :react-native-menu_menu:compileDebugKotlin FAILED                                                           

> Task :shopify_flash-list:compileDebugKotlin
w: file:///C:/Users/User/Downloads/.o/projectX/node_modules/@shopify/flash-list/android/src/main/kotlin/com/shopify/reactnative/flash_list/AutoLayoutView.kt:16:8 'interface RCTEventEmitter : Any, JavaScriptModule' is deprecated. Deprecated in Java.
w: file:///C:/Users/User/Downloads/.o/projectX/node_modules/@shopify/flash-list/android/src/main/kotlin/com/shopify/reactnative/flash_list/BlankAreaEvent.kt:22:18 This declaration overrides a deprecated member but is not marked as deprecated itself. Please add the '@Deprecated' annotation or suppress the diagnostic.
345 actionable tasks: 11 executed, 334 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: file:///C:/Users/User/Downloads/.o/projectX/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt:56:3 'onInterceptTouchEvent' overrides nothing.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-menu_menu:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. e: file:///C:/Users/User/Downloads/.o/projectX/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt:56:3 'onInterceptTouchEvent' overrides nothing. FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':react-native-menu_menu:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 4s.
info Run CLI with --verbose flag for more details.
```

**Environment:**

- React Native version: 0.77
- Platform: Android
- `react-native-menu` version: 1.2.1 

![Image](https://github.com/user-attachments/assets/67e82bd4-ca09-47e0-bf92-42425519eb81)

Thank you for such an amazing library! 💓🙏🫡

**Comment by TheAdamBorek** [comment]
+1

I'm also getting android compiling issues with RN 0.77

**Comment by edwinkcw** [comment]
+1

**Comment by TrustyTechSG** [comment]
Im also having this issue. any walkaround at the moment?

**Comment by mickyfazler** [comment]
💓Just wanted to confirm that PR #1022 completely solved this issue! Thanks to @compojoom for the fix, and to @quocluongha for sharing the .patch file that helped get it resolved!

**Comment by PatrickBokhove** [comment]
Any idea when this will be available through npm?

**Comment by TrustyTechSG** [comment]
May I ask when can we have a release on this? Big thanks.

**Comment by Naturalclar** [comment]
Sorry for the late release, just published a new package that should fix the issue!

**Comment by Chropez** [comment]
I still get what I believe is the same issue with version 1.2., RN 0.77 and expo 52.

Any ideas what it could be? 

![Image](https://github.com/user-attachments/assets/a627358f-2122-413c-8605-779a14a854f6)
