### ISSUE TITLE
Fatal error building iOS with v1.0.x & old arch

### ISSUE THREAD

**Issue by swrobel** [react-native-menu/menu#751]
```
node_modules/@react-native-menu/menu/ios/MenuViewManager.mm:10:9: fatal error: 'react_native_menu-Swift.h' file not found
#import <react_native_menu-Swift.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This seems to have been broken by #682 cc @SudoPlz 

react-native-menu 1.0.0
react-native 0.73.6

**Comment by fobos531** [comment]
also see #750

**Comment by hollanderbart** [comment]
Sorry for the negativity, but how can software be released this way? It surprises me each time.

**Comment by fobos531** [comment]
> Sorry for the negativity, but how can software be released this way? It surprises me each time.

For what it's worth, I just tried building the application on iOS and old arch (RN 0.73.6), and it worked just fine for me with v1.0.0

**Comment by antoniogoulao** [comment]
My workaround as to lower the version on `package.json` back to 0.9.1 and it worked again on iOS.

**Comment by marcoizzo** [comment]
same issue here

**Comment by fobos531** [comment]
Can confirm, this is happening for me as well on 1.0.1 and react native 0.73.7

**Comment by swrobel** [comment]
@SudoPlz could you please take a look at this

**Comment by Myst1024** [comment]
I was able to resolve this issue by updating `MenuViewManager.mm`:

```diff
 #import "MenuView.h"
 #else
 // OLD ARCH
-#import <react_native_menu-Swift.h>
+#import <react_native_menu/react_native_menu-Swift.h>
 #endif
 
 @interface MenuViewManager : RCTViewManager```

**Comment by swrobel** [comment]
@Myst1024 cool! Have you considered submitting as a PR?

**Comment by Silvan-M** [comment]
Also facing same problem, doing fix by @Myst1024 works. However it seems as if it needs to be changed after every run of `pod install`. PR would be great!

**Comment by JustJoostNL** [comment]
@Naturalclar can you consider reopening this? The problem still exists, see:

https://github.com/react-native-menu/menu/pull/794#issuecomment-2097759792
https://github.com/react-native-menu/menu/pull/794#issuecomment-2099037980

**Comment by JuanRdBO** [comment]
Still exists for me as well
