### PR TITLE
fix(#146,#70): android type mismatch

### LINKED ISSUE #70: Only safe (?.) or non-null asserted (!!.) calls are allowed on a null
I have build error in new ver 0.3.1:

image

    ext {
        buildToolsVersion = '29.0.2'
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlin_version = '1.3.50'
    }

### LINKED ISSUE #146: Type mismatch: inferred type is ReadableMap? but ReadableMap was expected
yarn run android throw below error 

e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (141, 38): Type mismatch: inferred type is ReadableMap? but ReadableMap was expected
e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (177, 34): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (177, 64): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (181, 35): Type mismatch: inferred type is ReadableMap? but ReadableMap was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-menu_menu:compileDebugKotlin'.
> Compilation error. See log for more details

I am using the latest version.

### PR DESCRIPTION
**Pull request by mateusz1913**
# Overview

Hi, this is fix for android compile errors related to type mismatch

Closes #146 
Closes #70 

The main problem was that some changes were introduced to ReadableMap & ReadableArray between RN version 0.64 & 0.63. In newer version, methods like `.getMap` are returning non-null values, when in older versions, these values were nullable.

**Solution:**
A few `.isNull` methods on ReadableMap/ReadableArray objects were added to code, together with `!= null` checks and some more `?.` 

# Test Plan

Try that on example app (RN 0.64) as well as older versions of RN (e.g. 0.63)

### CODE REVIEW

**Review by Naturalclar — APPROVED** [review]
@mateusz1913 verified that android builds on both RN 0.63 and 0.64, thanks so much!
