### PR TITLE
fix: android build on Expo SDK 55+56 / RN 0.83 / Kotlin 2.x

### LINKED ISSUE #1058: MenuView fails on iOS (Unimplemented) + Android (View config missing)
**Description**  
The `MenuView` component fails to render on both iOS and Android with different errors when using React Native's New Architecture:
- **iOS**: `Unimplemented component: <MenuView>`  
- **Android**: `View config not found for component 'MenuView'`  

**Steps to Reproduce**  
1. Install @react-native-menu/menu@1.2.3
2. Import and use `<MenuView>` in a component  
3. Run the app (iOS/Android)  
4. Error appears  

### **Expected Behavior**  
`MenuView` should render a functional menu on both platforms.  

### **Actual Behavior**  
- **iOS**: White screen/error with `Unimplemented component`  
- **Android**: Red screen with `View config not found`  

### **Environment**
| Key             | Value                         |
| --------------- | ----------------------------- |
| Library Version | react-native-menu/menu@1.2.3       |
| React           | 19.0.0                        |
| React Native    | 0.78.1                        |
|New Architecture|Enabled (Fabric & TurboModules)|
| Platform        | iOS & Android                 |

- **Screenshots**:  
Image

- **Troubleshooting Attempted**:
  - ✅ Reinstalled node_modules
  - ✅ Cleared Metro cache (`npx react-native start --reset-cache`)
  - ✅ Verified native linking (for Android/iOS)

### LINKED ISSUE #1167: Bug Report: "Val cannot be reassigned" error regression in v2.0.0
## Issue Description
The "Val cannot be reassigned" error that was previously fixed has reappeared in version 2.0.0, suggesting a regression in the codebase.

## Environment
- **React Native**: 0.74+
- **Library Version**: 2.0.0
- **Platform**: Android

### Background
- **Pre-v1.0.0**: The "Val cannot be reassigned" error was present in React Native 0.74+ [[issue #736](https://github.com/react-native-menu/menu/issues/736)]
- **v1.0.0**: Issue was resolved with [[PR #746](https://github.com/react-native-menu/menu/pull/746)]
android/src/main/java/com/reactnativemenu/MenuViewManagerBase.kt
`view.hitSlopRect = null` →  `view.setHitSlopRect(null)`
- **v1.2.0**: Further improvements were added, including the `setHitSlopRect` override method 
( android/src/main/java/com/reactnativemenu/MenuView.kt - `override fun setHitSlopRect` )
```kotlin
override fun setHitSlopRect(rect: Rect?) {
    super.setHitSlopRect(rect)
    mHitSlopRect = rect
    updateTouchDelegate()
}
```
- **v2.0.0**: **Regression occurred** - previous fixes appear to have been reverted

## Expected Behavior
The library version 2.0.0 should work without compilation errors on React Native 0.74+, as it did in versions 1.0.0 through 1.2.4.

## Actual Behavior
The "Val cannot be reassigned" compilation error has returned, breaking builds for React Native 0.74+ projects.

## Reproduction Steps
1. Use library version 2.0.0
2. Build project with React Native 0.74+
3. Encounter "Val cannot be reassigned" compilation error

## Possible Solution
Restore the fixes that were implemented in v1.0.0 (PR #746) and the enhancements from v1.2.4, particularly:
- The `setHitSlopRect` override method
- Using `view.setHitSlopRect(null)` instead of `view.hitSlopRect = null`

### PR DESCRIPTION
**Pull request by oobagi**
# Overview

v2.0.0 doesn't build on Android with Expo SDK 55 (RN 0.83, Kotlin 2.1.20). Two issues:

**`isNewArchitectureEnabled()` returns false on RN 0.83+** — RN 0.83 removed the `newArchEnabled` gradle property since new arch is now the only option. Without it the function defaults to false, the `com.facebook.react` plugin never gets applied, oldarch sources are used, and codegen is skipped. Result: "View config not found for component MenuView" at runtime. This PR defaults to true when the property is absent.

**`MenuView.kt` setter breaks under K2** — #1156 switched to property syntax for `hitSlopRect`, but K2 rejects `super.hitSlopRect = value` because it's `val` in the `ReactHitSlopView` interface. The self-assignment `mHitSlopRect = value` inside its own setter is also infinite recursion. Same bug that was fixed in v1.0.0 via #746. This PR uses the `field` keyword instead.

Closes #1167, Fixes #1058
Related: #1179, #1186, #1187

# Test Plan

- Build an Expo SDK 55 project with `@react-native-menu/menu` on Android
- Verify MenuView renders and popup opens on tap
- Verify hit slop works without stack overflow
- Verify old arch builds still work (property present and set to "true"/"false")

### CODE REVIEW

**Comment by 1kuko3** [comment]
This works on Expo 56, too!

**Comment by orientalperil** [comment]
Can this get merged and released?  This library is broken

File: android/build.gradle [hunk 1]
```diff
@@ -15,7 +15,10 @@ buildscript {
 }
 
 def isNewArchitectureEnabled() {
-  return rootProject.hasProperty("newArchEnabled") && rootProject.getProperty("newArchEnabled") == "true"
+  if (rootProject.hasProperty("newArchEnabled")) {
+    return rootProject.getProperty("newArchEnabled") == "true"
+  }
+  return true
```
Comment (Naturalclar) [inline android/build.gradle]: i believe this would cause breaking change as it would force apps without newArchEnabled to use the new  arch

Comment (oobagi) [reply android/build.gradle]: Good catch, thanks. I updated this to only default to New Architecture on RN 0.82+, where legacy architecture is no longer selectable. For earlier versions, it preserves the previous behavior and only uses the new-arch path when it is explicitly set.

**Review by Naturalclar — APPROVED** [review]
LGTM!
