### ISSUE TITLE
Android build fail on compileSdkVersion 33

### ISSUE THREAD

**Issue by Dajust** [react-native-menu/menu#488]
` Task :react-native-menu_menu:compileDebugKotlin FAILED`

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-menu_menu:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

The above error occurs when I update to increase `compileSdkVersion` to 33. Works fine when I reduce it to 31.

**Comment by arjendevos** [comment]
Same issue

**Comment by Naturalclar** [comment]
Fixed in v0.7.3 👍🏻
