### PR TITLE
Update MenuViewManager.mm

### LINKED ISSUE #751: Fatal error building iOS with v1.0.x & old arch
```
node_modules/@react-native-menu/menu/ios/MenuViewManager.mm:10:9: fatal error: 'react_native_menu-Swift.h' file not found
#import <react_native_menu-Swift.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This seems to have been broken by #682 cc @SudoPlz 

react-native-menu 1.0.0
react-native 0.73.6

### PR DESCRIPTION
**Pull request by Gregoirevda**
Fixes #751

### CODE REVIEW

**Review by Naturalclar — APPROVED** [review]
Thank you!

**Comment by JClackett** [comment]
any idea when we can expect a release? 🙌🏾

**Comment by Naturalclar** [comment]
@JClackett released in v1.0.2 🚀

**Comment by JClackett** [comment]
Hmm yeah I've been trying this but still getting this in 1.0.2:

```
❌  (../../node_modules/@react-native-menu/menu/ios/MenuViewManager.mm:10:9)

   8 | #else
   9 | // OLD ARCH
> 10 | #import <react_native_menu/react_native_menu-Swift.h>
     |         ^ 'react_native_menu/react_native_menu-Swift.h' file not found
  11 | #endif
  12 | 
  13 | @interface MenuViewManager : RCTViewManager
```

**Comment by JustJoostNL** [comment]
Same issue here still.

**Comment by swrobel** [comment]
It is a bit odd that although this fixed my iOS build issues, the `react_native_menu-Swift.h` file doesn't seem to exist anywhere, regardless of the path.

**Comment by JuanRdBO** [comment]
Still exists for me

**Comment by Gregoirevda** [comment]
@JuanRdBO seems to be fixed in 1.0.3

**Comment by JuanRdBO** [comment]
> @JuanRdBO seems to be fixed in 1.0.3

Sadly this still happens to me on 1.0.3 :-/

**Comment by JustJoostNL** [comment]
Yup

**Comment by Gregoirevda** [comment]
1.0.2 included this fix and 1.0.3 went back to 
```obj-c
#import <react_native_menu-Swift.h>
```

But the convention is `<ProductName/ProductModuleName-Swift.h>` which should be:
```obj-c
#import <react_native_menu/react_native_menu-Swift.h>
```

Could you confirm this works and it would then be good to revert the change @svbutko

**Comment by Gregoirevda** [comment]
@JustJoostNL @JuanRdBO Does it work if you downgrade to 1.0.2, `pod install` and build?

**Comment by JuanRdBO** [comment]
> @JustJoostNL @JuanRdBO Does it work if you downgrade to 1.0.2, `pod install` and build?

It works with 1.0.2! Why do you think it wouldn't work on the latest version?

**Comment by JClackett** [comment]
1.0.3 is working now

**Comment by Gregoirevda** [comment]
@svbutko I was expecting the import to only be executed in the old arch?
```obj-c
#ifdef RCT_NEW_ARCH_ENABLED
// NEW ARCH
#import "MenuView.h"
#else
// OLD ARCH
#import <react_native_menu-Swift.h>
#endif
```
